"""Initial migration.

Revision ID: e64c9ec78472
Revises: 
Create Date: 2024-03-29 18:22:07.139541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64c9ec78472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cafe():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe')
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade_cafe():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('verified')

    op.create_table('cafe',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(length=250), nullable=False),
    sa.Column('map_url', sa.TEXT(length=500), nullable=False),
    sa.Column('img_url', sa.TEXT(length=500), nullable=False),
    sa.Column('location', sa.TEXT(length=250), nullable=False),
    sa.Column('has_sockets', sa.BOOLEAN(), nullable=False),
    sa.Column('has_toilet', sa.BOOLEAN(), nullable=False),
    sa.Column('has_wifi', sa.BOOLEAN(), nullable=False),
    sa.Column('can_take_calls', sa.BOOLEAN(), nullable=False),
    sa.Column('seats', sa.TEXT(length=250), nullable=True),
    sa.Column('coffee_price', sa.TEXT(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

